"""baseline: video and action tables as of Part A/B

Revision ID: fb1f58bec396
Revises: 
Create Date: 2026-10-08 01:46:23.717089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb1f58bec396'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiktok_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_date', sa.DateTime(), nullable=True),
    sa.Column('user_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashtags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('local_video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('worth_rewatching_score', sa.Integer(), nullable=True),
    sa.Column('worth_rewatching_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_promo_code', sa.Boolean(), nullable=False),
    sa.Column('promo_code_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_dated_offer', sa.Boolean(), nullable=False),
    sa.Column('offer_deadline_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mentions_link_in_bio', sa.Boolean(), nullable=False),
    sa.Column('key_facts', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'DOWNLOADED', 'TRANSCRIBING', 'TRANSCRIBED', 'ANALYZING', 'DONE', 'SUBMITTED', 'ERROR', name='status'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_tiktok_url'), 'video', ['tiktok_url'], unique=True)
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SKILL', 'PROJECT', 'JOB', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'DRAFTED', 'NEEDS_INPUT', 'DONE', 'DISMISSED', 'FAILED', name='actionstatus'), nullable=False),
    sa.Column('brief', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_video_id'), 'action', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_video_id'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_video_tiktok_url'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
